[server]
headless = true
enableCORS = false
enableXsrfProtection = false
runOnSave = false
fileWatcherType = "none"

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false

[global]
developmentMode = false